version: '3.8'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kanban_prod
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanban_user -d kanban_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    environment:
      NODE_ENV: production
      DB_USERNAME: kanban_user
      DB_PASSWORD: kanban_password
      DB_NAME: kanban_prod
      HOST: database
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
    command: sh -c "npm run migrate && npm start"

  client:
    build: ./client/kanban
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  postgres_data: 